Implement Winston Logging Library
BediBot/BediBot-Rewrite pull request #35
Opened 2021-08-12 03:07 UTC by zaydtahir

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: Closes #28 

## What is the new behavior?

- Implemented Winston Logger

## Other information

Tests not created due to the nature of this PR

2021-08-12 03:08 UTC, zaydtahir commented
![image](https://user-images.githubusercontent.com/20825025/129132407-a695de6c-e5c2-43d3-9772-35386e1836ba.png)
![image](https://user-images.githubusercontent.com/20825025/129132430-a4817c28-b79a-44b9-baf9-00e4450bef00.png)

2021-08-12 17:02 UTC, sahil-kale requested changes
Looks good to me aside from one minor nit

2021-08-12 17:02 UTC, sahil-kale commented on src/utils/loggerUtil.ts
> +      filename: './logs/combined.log',
Can these filenames be made configurable in a common place, or at the top of the file for visibility? Or potentially pass them in as arguments when spooling up a logger instance?

2021-08-13 01:23 UTC, sahil-kale approved these changes

2021-08-13 01:25 UTC, merged